- Where_Are_You.xcodeproj/project.pbxproj
- Where_Are_You/Data/Network/Location/LocationService.swift
- Where_Are_You/Data/Network/Schedule/ScheduleAPI.swift
- Where_Are_You/Data/Network/Schedule/ScheduleService.swift
- Where_Are_You/Data/Repositories/LocationRepository.swift
- Where_Are_You/Data/Repositories/ScheduleRepository.swift
- Where_Are_You/Domain/UseCases/Loacation/GetLocationUseCase.swift
- Where_Are_You/Presentation/Main/FriendFeed/FriendFeedViewController.swift
- Where_Are_You/Presentation/Main/Mypage/ViewControllers/LocationBookmarkViewController.swift
- Where_Are_You/Presentation/Main/Mypage/ViewControllers/MyPageViewController.swift
- Where_Are_You/Presentation/Main/Mypage/ViewModels/LocationBookmarkViewModel.swift
- Where_Are_You/Presentation/Main/Mypage/Views/LocationBookMarkCell.swift
- Where_Are_You/Presentation/Main/NoDataView.swift
feat(#31): 위치 즐겨찾기
1. 위치 즐겨찾기 서버 통신 구현(API, Service, Repository, UseCase)
2. 데이터가 없을때 noDataView가 뜨게 설정 데이터가 있는 경우엔 tableView가 뜨도록 설정
3. 뷰모델에서 위치 즐겨찾기 정보를 받아오도록 연결
> feat: 마이페이지/위치 즐겨찾기

- Where_Are_You.xcodeproj/project.pbxproj
- Where_Are_You/Data/Models/Requests/Locations/FavoriteLocationBody.swift
- Where_Are_You/Data/Network/Location/LocationAPI.swift
- Where_Are_You/Data/Network/Location/LocationService.swift
- Where_Are_You/Data/Repositories/LocationRepository.swift
- Where_Are_You/Domain/UseCases/Loacation/PutLocationUseCase.swift
- Where_Are_You/Presentation/Main/Mypage/ViewControllers/LocationBookmarkViewController.swift
- Where_Are_You/Presentation/Main/Mypage/ViewModels/LocationBookmarkViewModel.swift
- Where_Are_You/Presentation/Main/Mypage/Views/LocationBookmarkView.swift
- Where_Are_You/Utils/HandleOutsideTap.swift
> feat(#31): 마이페이지/위치 즐겨찾기 완료

- Where_Are_You/Data/Models/Responses/Feed/GetBookMarkResponse.swift
- Where_Are_You/Presentation/Main/Mypage/Views/FeedBookMarkView.swift
- Where_Are_You/Presentation/Main/Schedule/Views/CreateScheduleView.swift
feat(#38): 마이페이지 / 피드 책갈피
1. 데이터 없는 뷰 추가
2. bookmarkFeedResponse 형식 수정
> feat(#38): 마이페이지 / 피드 책갈피

- Where_Are_You/Data/Models/Requests/Feed/FeedRequest.swift
- Where_Are_You/Presentation/Main/FriendFeed/Feeds/ViewControllers/AddFeedViewController.swift
- Where_Are_You/Presentation/Main/FriendFeed/Feeds/ViewModels/AddFeedViewModel.swift
- Where_Are_You/Presentation/Main/FriendFeed/Feeds/Views/FeedDetailBoxView.swift
- Where_Are_You/Presentation/Main/FriendFeed/Feeds/Views/FeedsTableViewCell.swift
- Where_Are_You/Utils/MultipartFormDataHelper.swift
> feat(#6): 피드 생성 로직 추가

- Where_Are_You.xcodeproj/project.pbxproj
- Where_Are_You/Domain/UseCases/Schedule/GetDDayScheduleUseCase.swift
- Where_Are_You/Domain/UseCases/Schedule/GetScheduleListUseCase.swift
- Where_Are_You/Domain/UseCases/Schedule/GetScheduleUseCase.swift
- Where_Are_You/Presentation/Main/FriendFeed/Feeds/ViewControllers/AddFeedViewController.swift
- Where_Are_You/Presentation/Main/FriendFeed/Feeds/ViewModels/AddFeedViewModel.swift
- Where_Are_You/Presentation/Main/FriendFeed/Feeds/Views/AddFeed/ScheduleDropDownView.swift
feat(#35): getScheduleUseCase 추가
> feat(#35): getScheduleUseCase 추가

- Where_Are_You.xcodeproj/project.pbxproj
- Where_Are_You/Data/Models/Responses/Schedule/GetScheduleResponse.swift
- Where_Are_You/Data/Network/Schedule/ScheduleAPI.swift
- Where_Are_You/Data/Network/Schedule/ScheduleService.swift
- Where_Are_You/Data/Repositories/ScheduleRepository.swift
- Where_Are_You/Domain/UseCases/Schedule/DeleteScheduleUseCase.swift
- Where_Are_You/Domain/UseCases/Schedule/GetScheduleUseCase.swift
- Where_Are_You/Domain/UseCases/Schedule/PostEcceptScheduleUseCase.swift
- Where_Are_You/Domain/UseCases/Schedule/PostScheduleUseCase.swift
- Where_Are_You/Domain/UseCases/Schedule/PutScheduleUseCase.swift
- Where_Are_You/Presentation/Main/FriendFeed/Feeds/ViewControllers/AddFeedViewController.swift
- Where_Are_You/Presentation/Main/FriendFeed/Feeds/ViewModels/AddFeedViewModel.swift
- Where_Are_You/Presentation/Main/FriendFeed/Feeds/Views/AddFeed/AddFeedView.swift
- Where_Are_You/Presentation/Main/FriendFeed/Feeds/Views/AddFeed/CustomView.swift
> feat(#35): 일정 API 추가

- Where_Are_You/Data/Models/Requests/Friend/FriendRequest/AcceptFriendRequestBody.swift
- Where_Are_You/Data/Models/Responses/Member/MemberDetailsResponse.swift
- Where_Are_You/Presentation/Main/FriendFeed/Friends/ViewModels/FriendsViewModel.swift
- Where_Are_You/Presentation/Main/FriendFeed/Friends/ViewModels/ManageFriendsViewModel.swift
- Where_Are_You/Presentation/Main/FriendFeed/Friends/Views/FriendDetailView.swift
- Where_Are_You/Presentation/Main/FriendFeed/Friends/Views/FriendsView.swift
- Where_Are_You/Presentation/Main/FriendFeed/Friends/Views/ManageFriendsView.swift
- Where_Are_You/Presentation/Main/FriendFeed/Friends/Views/SearchFriendsView.swift
- Where_Are_You/Presentation/Main/Mypage/ViewControllers/MyPageViewController.swift
> fix(#60): 친구 목록 가져오기 오류 해결

- Where_Are_You/Data/Repositories/MemberRepository.swift
- Where_Are_You/Presentation/Main/Mypage/ViewControllers/MyPageViewController.swift
- Where_Are_You/Presentation/Main/Mypage/ViewModels/MyPageViewModel.swift
feat(#35): putProfileImage API 성공시 UserDefaultsManager의 profileImageURL값 변경
> feat(#35): putProfileImage API 성공시 UserDefaultsManager의 profileImageURL값 변경

- Where_Are_You.xcodeproj/project.pbxproj
- Where_Are_You/Presentation/Main/Home/ViewControllers/MainHomeViewController.swift
- Where_Are_You/Presentation/Main/MainTabBarController.swift
- Where_Are_You/Presentation/Main/Mypage/ViewControllers/AccountDelete/AgreementAcountDeletionViewController.swift
- Where_Are_You/Presentation/Main/Mypage/ViewControllers/AccountDelete/CommentDeletionViewController.swift
- Where_Are_You/Presentation/Main/Mypage/ViewControllers/MyPageViewController.swift
- Where_Are_You/Presentation/Main/Mypage/ViewModels/AccountDelete/AgreementViewModel.swift
- Where_Are_You/Presentation/Main/Mypage/Views/AccountDelete/AgreementAcountDeletionView.swift
- Where_Are_You/Presentation/Main/Mypage/Views/AccountDelete/CommentAccountDeletionView.swift
- Where_Are_You/Presentation/Main/Mypage/Views/AccountDelete/CommonAccountBoxView.swift
feat(#86): 회원탈퇴 주의사항 확인 뷰, 뷰컨트롤러 구현 완료
> feat(#86): 회원탈퇴 주의사항 확인 뷰, 뷰컨트롤러 구현 완료

- Where_Are_You.xcodeproj/project.pbxproj
- Where_Are_You/Presentation/Main/Mypage/ViewControllers/AccountDelete/CommentDeletionViewController.swift
- Where_Are_You/Presentation/Main/Mypage/Views/AccountDelete/CommentAccountDeletionView.swift
- Where_Are_You/Presentation/Main/Mypage/Views/AccountDelete/InputFieldTableViewCell.swift
- Where_Are_You/Presentation/Main/Mypage/Views/AccountDelete/ReasonSelectionTableViewCell.swift
- Where_Are_You/Utils/Extensions.swift
feat(#86): 회원탈퇴 이유 뷰 추가(기타 직접입력 텍스트필드 부분 수정중
> feat(#86): 회원탈퇴 이유 뷰 추가(기타 직접입력 텍스트필드 부분 수정중

- Where_Are_You/Data/Models/Responses/Schedule/DDayScheduleResponse.swift
- Where_Are_You/Domain/Entities/DDay.swift
- Where_Are_You/Presentation/Main/FriendFeed/Feeds/ViewControllers/AddFeedViewController.swift
- Where_Are_You/Presentation/Main/FriendFeed/Feeds/ViewModels/AddFeedViewModel.swift
- Where_Are_You/Presentation/Main/Home/ViewControllers/DDayViewController.swift
- Where_Are_You/Presentation/Main/Home/ViewModels/DDayViewModel.swift
- Where_Are_You/Presentation/Main/Home/Views/DDayCell.swift
- Where_Are_You/Presentation/Main/Home/Views/DDayView.swift
- Where_Are_You/Presentation/Main/Home/Views/HomeFeedCollectionViewCell.swift
- Where_Are_You/Presentation/Main/Home/Views/HomeFeedView.swift
- Where_Are_You/Presentation/Main/Mypage/ViewControllers/AccountDelete/CheckPasswordViewController.swift
- Where_Are_You/Presentation/Main/Mypage/ViewControllers/AccountDelete/CommentDeletionViewController.swift
- Where_Are_You/Presentation/Main/Mypage/ViewControllers/AccountDelete/CompleteDeleteViewController.swift
- Where_Are_You/Presentation/Main/Mypage/ViewControllers/AccountDelete/ReagreementAcountDeletionViewController.swift
- Where_Are_You/Presentation/Main/Mypage/Views/AccountDelete/CheckPasswordView.swift
- Where_Are_You/Presentation/Main/Mypage/Views/AccountDelete/CompleteDeleteView.swift
refactor(#23): DDya API Response 값 수정 -> 디데이 안뜨던 문제 해결, 홈피드 화면 leading, trailing 값 수정.
> refactor(#23): DDya API Response 값 수정 -> 디데이 안뜨던 문제 해결, 홈피드 화면 leading, trailing 값 수정.

- Where_Are_You/Presentation/Main/FriendFeed/Feeds/ViewModels/FeedViewModel.swift
- Where_Are_You/Presentation/Main/FriendFeed/Feeds/Views/FeedsTableViewCell.swift
- Where_Are_You/Presentation/Main/Home/ViewControllers/HomeFeedViewController.swift
- Where_Are_You/Presentation/Main/Home/Views/HomeFeedCollectionViewCell.swift
- Where_Are_You/Utils/Extensions.swift
feat(#23, #46): 피드 content text 더 보기 구현
> feat(#23, #46): 피드 content text 더 보기 구현

- Where_Are_You/Presentation/Main/FriendFeed/Feeds/Views/DetailFeed/CommonFeedView.swift
Style(#92): 상세 피드 descriptionLable 수정
1. numberOfLines  3 -> 0 으로 수정
2. lineBreakMode 삭제
> Style(#92): 상세 피드 descriptionLable 수정

- Where_Are_You.xcodeproj/project.pbxproj
- Where_Are_You/Data/Network/Schedule/ScheduleService.swift
- Where_Are_You/Data/Repositories/ScheduleRepository.swift
- Where_Are_You/Domain/UseCases/Schedule/GetDailyScheduleUseCase.swift
- Where_Are_You/Presentation/Main/Home/ViewModels/HomeDailyScheduleViewModel.swift
feat(#99, #35): getDailySchedule API 수정
> feat(#99, #35): getDailySchedule API 수정

- Where_Are_You/Presentation/Login/Login/ViewControllers/LoginViewController.swift
- Where_Are_You/Presentation/Login/Login/Views/LoginView.swift
- Where_Are_You/Presentation/Main/FriendFeed/Feeds/Views/FeedsTableViewCell.swift
- Where_Are_You/Presentation/Main/Home/ViewControllers/BottomSheetViewController.swift
- Where_Are_You/Presentation/Main/Home/Views/BottomSheetView.swift
- Where_Are_You/Presentation/Main/Home/Views/MainHomeView.swift
- Where_Are_You/Utils/Customs/CustomButton.swift
- Where_Are_You/Utils/Customs/CustomLabel.swift
- Where_Are_You/Utils/Extensions.swift
> feat(#103, #99): 홈화면 바텀시트 추가

- Where_Are_You.xcodeproj/project.pbxproj
- Where_Are_You/Presentation/Login/SingUp/ViewControllers/SignUpFormViewController.swift
- Where_Are_You/Presentation/Login/SingUp/ViewModels/SignUpViewModel.swift
- Where_Are_You/Presentation/Login/SingUp/Views/SignUpFormView.swift
- Where_Are_You/Presentation/Login/SingUp/Views/TermsAgreementView.swift
- Where_Are_You/Utils/Customs/CustomButton.swift
- Where_Are_You/Utils/Customs/CustomTextField.swift
- Where_Are_You/Utils/Extensions.swift
- Where_Are_You/Utils/ValidationHelper.swift
Refactor(#103): SignUpView 리팩토링 완료
> Refactor(#103): SignUpView 리팩토링 완료

- Where_Are_You.xcodeproj/project.pbxproj
- Where_Are_You/Presentation/Login/FindAccount/ViewControllers/AccountSearchViewController.swift
- Where_Are_You/Presentation/Login/FindAccount/ViewControllers/PasswordResetViewController.swift
- Where_Are_You/Presentation/Login/Login/ViewControllers/AccountLoginController.swift
- Where_Are_You/Presentation/Login/Login/ViewControllers/LoginViewController.swift
- Where_Are_You/Presentation/Login/Login/Views/AccountLoginView.swift
- Where_Are_You/Presentation/Login/SingUp/ViewControllers/SocialLinkViewController.swift
- Where_Are_You/Presentation/Login/SingUp/ViewControllers/SocialSignUpViewController.swift
- Where_Are_You/Presentation/Login/SingUp/ViewModels/SocialLinkViewModel.swift
- Where_Are_You/Presentation/Login/SingUp/ViewModels/SocialSignUpViewModel.swift
- Where_Are_You/Presentation/Login/SingUp/Views/FinishRegisterview.swift
- Where_Are_You/Presentation/Login/SingUp/Views/SignUpFormView.swift
- Where_Are_You/Presentation/Login/SingUp/Views/SocialLinkView.swift
- Where_Are_You/Presentation/Login/SingUp/Views/SocialSignUpView.swift
- Where_Are_You/Presentation/Login/SingUp/Views/TermsAgreementView.swift
- Where_Are_You/SceneDelegate.swift
> Feat(#98): sns link view 추가

- Where_Are_You/Presentation/Login/Login/ViewControllers/LoginViewController.swift
- Where_Are_You/Presentation/Login/SingUp/ViewControllers/SocialSignUpViewController.swift
- Where_Are_You/Presentation/Login/SingUp/ViewModels/SignUpViewModel.swift
- Where_Are_You/Presentation/Login/SingUp/ViewModels/SocialSignUpViewModel.swift
- Where_Are_You/Presentation/Main/Mypage/ViewControllers/FeedArchiveViewController.swift
- Where_Are_You/Presentation/Main/Mypage/ViewControllers/FeedBookMarkViewController.swift
- Where_Are_You/Presentation/Main/Mypage/ViewControllers/LocationBookmarkViewController.swift
- Where_Are_You/Utils/Customs/CustomTextField.swift
feat(#98): 애플 회원가입시 socialSignUpView로 넘어가는 로직 구현
> feat(#98): 애플 회원가입시 socialSignUpView로 넘어가는 로직 구현

- Where_Are_You/Data/Models/Requests/Member/MemberSnsBody.swift
- Where_Are_You/Presentation/Login/CommonDescription.swift
- Where_Are_You/Presentation/Login/FindAccount/ViewControllers/AccountSearchViewController.swift
- Where_Are_You/Presentation/Login/FindAccount/ViewModels/AcoountSearchViewModel.swift
- Where_Are_You/Presentation/Login/FindAccount/Views/AccountCheckView.swift
- Where_Are_You/Presentation/Login/FindAccount/Views/AccountSearchView.swift
- Where_Are_You/Presentation/Login/FindAccount/Views/PasswordResetView.swift
- Where_Are_You/Presentation/Login/Login/ViewControllers/AccountLoginController.swift
- Where_Are_You/Presentation/Login/Login/ViewControllers/LoginViewController.swift
- Where_Are_You/Presentation/Login/SingUp/ViewControllers/SignUpFormViewController.swift
- Where_Are_You/Presentation/Login/SingUp/ViewControllers/SocialSignUpViewController.swift
- Where_Are_You/Presentation/Login/SingUp/ViewControllers/TermsAgreementViewController.swift
- Where_Are_You/Presentation/Login/SingUp/ViewModels/SocialLinkViewModel.swift
- Where_Are_You/Presentation/Login/SingUp/ViewModels/SocialSignUpViewModel.swift
- Where_Are_You/Presentation/Login/SingUp/Views/SignUpFormView.swift
- Where_Are_You/Presentation/Login/SingUp/Views/TermsAgreementView.swift
- Where_Are_You/Presentation/Main/FriendFeed/Feeds/ViewControllers/AddFeedViewController.swift
- Where_Are_You/Presentation/Main/FriendFeed/Feeds/ViewControllers/EditFeedViewController.swift
- Where_Are_You/Presentation/Main/FriendFeed/Feeds/Views/AddFeed/AddFeedView.swift
- Where_Are_You/Presentation/Main/Mypage/ViewControllers/AccountDelete/CheckPasswordViewController.swift
- Where_Are_You/Presentation/Main/Mypage/ViewControllers/MyDetailManageViewcontroller.swift
- Where_Are_You/Presentation/Main/Mypage/Views/MyDetailManageView.swift
- Where_Are_You/Utils/APIError.swift
- Where_Are_You/Utils/Customs/CustomButton.swift
- Where_Are_You/Utils/Customs/CustomTextField.swift
Refactor(#103): 로그인, 회원가입, 계정찾기 QA 1창 수정 완료
> Refactor(#103): 로그인, 회원가입, 계정찾기 QA 1창 수정 완료

- Where_Are_You/Presentation/Login/SingUp/ViewControllers/SignUpFormViewController.swift
- Where_Are_You/Presentation/Login/SingUp/ViewModels/SignUpViewModel.swift
- Where_Are_You/Utils/ValidationHelper.swift
> Fix(#124): SignUp

- Where_Are_You/Data/Network/Member/MemberAPI.swift
- Where_Are_You/Presentation/Main/Mypage/ViewControllers/MyDetailManageViewcontroller.swift
- Where_Are_You/Presentation/Main/Mypage/ViewControllers/MyPageViewController.swift
- Where_Are_You/Presentation/Main/Mypage/Views/MyDetailManageView.swift
- Where_Are_You/Utils/Customs/CustomTextField.swift
- Where_Are_You/Utils/Extensions.swift
Refactor(#103): MyPage - Detail
마이페이지 - 내정보관리 2025버젼 리팩토링 완료
> Refactor(#103): MyPage - Detail

- Where_Are_You.xcodeproj/project.pbxproj
- Where_Are_You/Data/Repositories/MemberRepository.swift
- Where_Are_You/Domain/UseCases/Member/DeleteMemberUseCase.swift
- Where_Are_You/Presentation/Login/Login/ViewControllers/AccountLoginController.swift
- Where_Are_You/Presentation/Login/SingUp/ViewControllers/SignUpFormViewController.swift
- Where_Are_You/Presentation/Main/Mypage/ViewControllers/AccountDelete/CheckPasswordViewController.swift
- Where_Are_You/Presentation/Main/Mypage/ViewControllers/LocationBookmarkViewController.swift
- Where_Are_You/Presentation/Main/Mypage/ViewModels/DeleteMemberViewModel.swift
- Where_Are_You/Presentation/Main/Mypage/Views/AccountDelete/AgreementAcountDeletionView.swift
- Where_Are_You/Presentation/Main/Mypage/Views/AccountDelete/CheckPasswordView.swift
- Where_Are_You/Presentation/Main/Mypage/Views/AccountDelete/CommentAccountDeletionView.swift
- Where_Are_You/Presentation/Main/Mypage/Views/AccountDelete/CommonAccountBoxView.swift
- Where_Are_You/Presentation/Main/Mypage/Views/AccountDelete/CompleteDeleteView.swift
- Where_Are_You/Presentation/Main/Mypage/Views/AccountDelete/ReasonSelectionTableViewCell.swift
- Where_Are_You/Presentation/Main/Mypage/Views/LocationBookMarkCell.swift
- Where_Are_You/Presentation/Main/Mypage/Views/LocationBookmarkView.swift
- Where_Are_You/Presentation/Main/NoDataView.swift
Refactor(#103): 위치즐겨찾기, 회원탈퇴 리팩토링/ Fix(#124): 회원탈퇴 QA 오류 픽스
1. 위치 즐겨찾기 2025버젼 리팩토링 완료
2. 회원탈퇴 2025버젼 리팩토링 완료
3. 회원탈퇴 완료시 로그인화면으로 넘어가게 하는 뷰로 이동이 안되는 오류 해결
> Refactor(#103): 위치즐겨찾기, 회원탈퇴 리팩토링/ Fix(#124): 회원탈퇴 QA 오류 픽스

- Where_Are_You.xcodeproj/project.pbxproj
- Where_Are_You/Data/Models/Responses/Schedule/GetScheduleResponse.swift
- Where_Are_You/Data/Network/Schedule/ScheduleService.swift
- Where_Are_You/Data/Repositories/ScheduleRepository.swift
- Where_Are_You/Domain/UseCases/Schedule/GetMonthlyScheduleUseCase.swift
- Where_Are_You/Domain/UseCases/Schedule/GetScheduleUseCase.swift
- Where_Are_You/Presentation/Main/Schedule/ViewModels/CreateScheduleViewModel.swift
- Where_Are_You/Presentation/Main/Schedule/ViewModels/ScheduleDetailViewModel.swift
- Where_Are_You/Presentation/Main/Schedule/ViewModels/ScheduleViewModel.swift
- Where_Are_You/Presentation/Main/Schedule/Views/ScheduleView.swift
- Where_Are_You/Utils/Extensions.swift
일정을 표시하기 전 정렬 로직을 통해 우선순위 할당
1. 연속 일정이 단일 일정보다 우선
2. 둘 다 연속 일정인 경우, 일정 기간이 길 수록 우선
3. 이외에는 먼저 추가된 일정이 우선
> fix(#121): 1차 QA 버그사항 수정 - 연속 날짜 일정 조회 시 계단식 표시되는 오류 해결

- Where_Are_You/Presentation/Main/FriendFeed/Friends/ViewModels/SearchFriendsViewModel.swift
- Where_Are_You/Presentation/Main/FriendFeed/Friends/Views/CommonFriensView.swift
- Where_Are_You/Presentation/Main/FriendFeed/Friends/Views/SearchFriendsView.swift
- Where_Are_You/Presentation/Main/Location/Views/ConfirmLocationView.swift
- Where_Are_You/Presentation/Main/Location/Views/SearchLocationView.swift
- Where_Are_You/Presentation/Main/Schedule/Views/CreateScheduleView.swift
- Where_Are_You/Presentation/Main/Schedule/Views/ScheduleDetailView.swift
- Where_Are_You/Presentation/Main/Schedule/Views/ScheduleView.swift
- SearchLocationView
- ConfirmLocationView
- SearchFriendsView
> fix(#121): 1차 QA 버그사항 수정 - 모달 시트로 띄우던 뷰 fullScreenCover로 변환

- Where_Are_You/Presentation/Main/Home/ViewControllers/HomeFeedViewController.swift
- Where_Are_You/Presentation/Main/Home/Views/HomeFeedCollectionViewCell.swift
Fix(#103): 홈화면 피드
홈화면 피드의 "... 더보기" 를 누르면 해당 피드의 디테일 피드 화면으로 넘어가는 로직 -> 피드 셀을 누르면 디테일 피드로 넘어가는 로직으로 수정
> Fix(#103): 홈화면 피드

- Where_Are_You.xcodeproj/project.pbxproj
- Where_Are_You/Data/Models/Responses/Member/ModifyProfileImage.swift
- Where_Are_You/Data/Network/Member/MemberService.swift
- Where_Are_You/Data/Repositories/MemberRepository.swift
Feat(#35): put-ProfileImage
프로필 이미지 변경 성공시 서버에서 URL값 리턴 받아 userDefaultManager에 추가하는 로직
> Feat(#35): put-ProfileImage

- Where_Are_You/Presentation/Main/FriendFeed/Feeds/ViewControllers/AddFeedViewController.swift
- Where_Are_You/Presentation/Main/Home/ViewControllers/BottomSheetViewController.swift
> feat(#23): 홈화면/바텀시트 완료

- Where_Are_You/Presentation/Login/Login/Views/LoginView.swift
- Where_Are_You/Presentation/Login/SingUp/ViewControllers/TermsAgreementViewController.swift
- Where_Are_You/Presentation/Login/SingUp/Views/TermsAgreementView.swift
> refactor(#151): 로그인 선택 방식 수정

- Where_Are_You/Presentation/Main/FriendFeed/Feeds/ViewControllers/FeedsViewController.swift
- Where_Are_You/Presentation/Main/FriendFeed/Feeds/Views/FeedsTableViewCell.swift
- Where_Are_You/Presentation/Main/FriendFeed/Feeds/Views/FeedsView.swift
- Where_Are_You/Presentation/Main/Mypage/ViewControllers/FeedArchiveViewController.swift
- Where_Are_You/Presentation/Main/Mypage/ViewControllers/FeedBookMarkViewController.swift
refactor(#144): 피드 수정
1. 피드뷰에서 scrollview, contentview 지우고 테이블뷰만 남기기 (스크롤 가능한 뷰 안에 스크롤뷰를 넣는걸 애플에서 지양하기에)
> refactor(#144): 피드 수정

- Where_Are_You.xcodeproj/project.pbxproj
- Where_Are_You/Presentation/Login/SingUp/ViewControllers/TermsAgreementViewController.swift
- Where_Are_You/Presentation/Login/SingUp/ViewControllers/TermsWebViewController.swift
> feat(#151): 약관 동의 추가 완료

- Where_Are_You.xcodeproj/project.pbxproj
- Where_Are_You/Presentation/Main/FriendFeed/Feeds/ViewControllers/AddFeedViewController.swift
- Where_Are_You/Presentation/Main/FriendFeed/Feeds/ViewControllers/FeedsViewController.swift
- Where_Are_You/Presentation/Main/FriendFeed/Feeds/ViewModels/FeedViewModel.swift
- Where_Are_You/Presentation/Main/Home/ViewControllers/BannerViewController.swift
- Where_Are_You/Presentation/Main/Home/ViewControllers/DDayViewController.swift
- Where_Are_You/Presentation/Main/Home/ViewControllers/MainHomeViewController.swift
fix(#161): 피드 리스트 오류 수정
피드 리스트 데이터를 두번 받아와서 두개의 데이터를 불러오던 오류 수정
> fix(#161): 피드 리스트 오류 수정

- Where_Are_You.xcodeproj/project.pbxproj
- Where_Are_You/Presentation/Login/CommonDescription.swift
- Where_Are_You/Presentation/Login/SingUp/ViewControllers/SignUpFormViewController.swift
- Where_Are_You/Presentation/Login/SingUp/ViewModels/SignUpViewModel.swift
- Where_Are_You/Presentation/Login/SingUp/Views/SignUpFormView.swift
refactor(#151): 회원가입 리팩토링
1. 회원가입/ 오류 문구 수정
2. 회원가입/ 이메일 부분 플로우 수정
3. 비밀번호 가리기 온오프 버튼 추가
> refactor(#151): 회원가입 리팩토링

- Podfile
- Podfile.lock
- Where_Are_You.xcodeproj/project.pbxproj
- Where_Are_You/AppDelegate.swift
- Where_Are_You/Presentation/Login/Login/Views/AccountLoginView.swift
- Where_Are_You/Presentation/Login/SingUp/Views/SignUpFormView.swift
- Where_Are_You/Presentation/Main/FriendFeed/Feeds/Views/FeedsView.swift
fix(#166): 회원가입 키보드에 가려지는 오류 수정
1. scrollview, contentview, keyboardlayoutguide를 사용해서 키보드가 올라올시 scrollview의 높이 조절해서 해결
> fix(#166): 회원가입 키보드에 가려지는 오류 수정

- Where_Are_You.xcodeproj/project.pbxproj
- Where_Are_You/Presentation/Main/FriendFeed/FriendFeedTitleView.swift
- Where_Are_You/Presentation/Main/FriendFeed/FriendFeedViewController.swift
refactor(#144): 피드,친구 타이틀뷰 수정
1. 네비게이션바에서 커스텀 뷰로 변경해서 홈화면과의 타이틀뷰 간의 이질감 수정
> refactor(#144): 피드,친구 타이틀뷰 수정

- Where_Are_You/Presentation/Main/FriendFeed/Feeds/ViewModels/FeedDetailViewModel.swift
- Where_Are_You/Presentation/Main/FriendFeed/Feeds/Views/DetailFeed/FeedDetailView.swift
- Where_Are_You/Presentation/Main/FriendFeed/Feeds/Views/DetailFeed/FeedParticipantView.swift
- Where_Are_You/Utils/Customs/GradientButton.swift
Feat(#196): 상세피드 버튼 설정
1. 상세피드 버튼 - 피드 작성 여부에 따라 버튼색 변경, 선택 여부에 따라 버튼색 변경
> Feat(#196): 상세피드 버튼 설정

- Where_Are_You/Presentation/Login/CommonDescription.swift
- Where_Are_You/Presentation/Login/FindAccount/ViewControllers/AccountSearchViewController.swift
- Where_Are_You/Presentation/Login/SingUp/ViewControllers/TermsAgreementViewController.swift
- Where_Are_You/Presentation/Login/SingUp/ViewControllers/TermsWebViewController.swift
- Where_Are_You/Presentation/Main/FriendFeed/Feeds/ViewControllers/AddFeedViewController.swift
- Where_Are_You/Presentation/Main/FriendFeed/Feeds/ViewControllers/FeedsViewController.swift
- Where_Are_You/Presentation/Main/FriendFeed/Feeds/Views/FeedDetailBoxView.swift
- Where_Are_You/Presentation/Main/FriendFeed/Feeds/Views/FeedsTableViewCell.swift
- Where_Are_You/Presentation/Main/Mypage/ViewControllers/FeedArchiveViewController.swift
- Where_Are_You/Presentation/Main/Mypage/ViewControllers/FeedBookMarkViewController.swift
- Where_Are_You/Presentation/Main/Mypage/ViewControllers/MyDetailManageViewcontroller.swift
- Where_Are_You/Presentation/Main/Mypage/ViewModels/FeedArchiveViewModel.swift
- Where_Are_You/Presentation/Main/Mypage/ViewModels/FeedBookMarkViewModel.swift
- Where_Are_You/Presentation/Main/Mypage/Views/MyPageView.swift
- Where_Are_You/Utils/ValidationHelper.swift
Fix(#189): 2차 QA 수정
1. 피드화면에서 옵션버튼들 스크롤할때 사라지지 않는 문제 해결
2. 회원가입, 아이디찾기 UI 수정
3. 피드 보관함, 피드 북마크 새로고침 기능 추가
4. 피드 보관함, 피드 북마크 추가 옵션 버튼 위치 이상하게 뜨던 에러 해결
> Fix(#189): 2차 QA 수정

- Where_Are_You/Presentation/Login/FindAccount/ViewControllers/AccountSearchViewController.swift
- Where_Are_You/Presentation/Login/FindAccount/Views/PasswordResetView.swift
- Where_Are_You/Presentation/Login/SingUp/Views/SignUpFormView.swift
- Where_Are_You/Presentation/Login/SingUp/Views/TermsAgreementView.swift
- Where_Are_You/Presentation/Main/FriendFeed/Feeds/Views/FeedDetailBoxView.swift
Feat(#189): 피드, login UI 수정
1. 피드 리스트 - 참가자뷰 gradient 추가
2. login - 약관동의 버튼, 비밀번호 숨기기 버튼 layout 수정
3. 계정찾기 - 이메일 텍스트 필드 입력시 resetUI 함수 추가
> Feat(#189): 피드, login UI 수정
